<?php
/*Название и ссылки на модели*/
return $list_model = [
    'audi-100.html' => '100',
    'audi-10-0C4.html' => '10 0C4',
    'audi-80.html' => '80',
    'audi-90.html' => '90',
    'audi-200.html' => '200',
    'audi-A1.html' => 'A1',
    'audi-A2.html' => 'A2',
    'audi-A3.html' => 'A3',
    'audi-A4.html' => 'A4',
    'audi-A5.html' => 'A5',
    'audi-A6.html' => 'A6',
    'audi-A7.html' => 'A7',
    'audi-A8.html' => 'A8',
    'audi-A-4B5.html' => 'A 4B5 ',
    'audi-A-4allroad.html' => 'A 4allroad',
    'audi-A-6allroad.html' => 'A 6allroad',
    'audi-A-6C6.html' => 'A 6C6 ',
    'audi-A-6C5.html' => 'A 6C5',
    'audi-A-8D2.html' => 'A 8D2',
    'audi-Allroad.html' => 'Allroad',
    'audi-C4.html' => 'C4',
    'audi-Q2.html' => 'Q2',
    'audi-Q3.html' => 'Q3',
    'audi-Q5.html' => 'Q5',
    'audi-Q6.html' => 'Q6',
    'audi-Q7.html' => 'Q7',
    'audi-R8.html' => 'R8',
    'audi-Coupe.html' => 'Coupe',
    'audi-RS.html' => 'RS',
    'audi-R-SQ3.html' => 'R SQ3',
    'audi-RS2.html' => 'RS2',
    'audi-RS3.html' => 'RS3',
    'audi-RS4.html' => 'RS4',
    'audi-RS5.html' => 'RS5',
    'audi-RS6.html' => 'RS6',
    'audi-RS7.html' => 'RS7',
    'audi-S1.html' => 'S1',
    'audi-S2.html' => 'S2',
    'audi-S3.html' => 'S3',
    'audi-S4.html' => 'S4',
    'audi-S5.html' => 'S5',
    'audi-S6.html' => 'S6',
    'audi-S7.html' => 'S7',
    'audi-S8.html' => 'S8',
    'audi-SQ5.html' => 'SQ5',
    'audi-SQ7.html' => 'SQ7',
    'audi-TT.html' => 'TT',
    'audi-T-TRS.html' => 'T TRS',
    'audi-TTS.html' => 'TTS',
    'audi-V8.html' => 'V8',
    'audi-quattro.html' => 'quattro',

];

